name: close
description: Close pull request from a PR comment
inputs:
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  permissions:
    description: Permissions to require for the command
    required: false
    default: write,maintain,admin
  pull-request-url:
    description: The Pull Request URL
    required: false
    default: ${{ github.event.issue.pull_request.html_url }}
  reaction:
    description: Reaction to add to the triggering comment
    required: false
    default: rocket
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
  username:
    description: Username
    required: false
    default: github-actions
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: .close
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
        skip_ci: true
    - id: stack
      uses: shikanime-studio/actions/stack@main
      if: steps.command.outputs.continue == 'true'
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-url: ${{ inputs.pull-request-url }}
    - id: pull_request
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        INFO_METHOD: ${{ steps.stack.outputs.method }}
        PARAMS: ${{ steps.command.outputs.params }}
      run: |
        METHOD=""

        if [ -n "$PARAMS" ]; then
          case "$PARAMS" in
            ghstack)
              METHOD="ghstack"
              ;;
            slpr)
              METHOD="sapling-pull-request"
              ;;
            ghpr)
              METHOD="github-pull-request"
              ;;
            *)
              echo "Unknown close method param '$PARAMS'. Expected 'ghstack', 'slpr' or 'ghpr'."
              exit 1
              ;;
          esac
        else
          METHOD="$INFO_METHOD"
        fi

        echo "method=$METHOD" >> "$GITHUB_OUTPUT"
      if: steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        EXTRA_ARGS: ${{ inputs.extra-args }}
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
        REGISTRY: ${{ inputs.registry }}
        USERNAME: ${{ inputs.username }}
      run: |
        GHSTACKRC_PATH=$(mktemp)
        trap 'rm -f "$GHSTACKRC_PATH"' EXIT
        cat > "$GHSTACKRC_PATH" <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = $GH_TOKEN
        github_username = $USERNAME
        EOF

        nix run "$REGISTRY#ghstack" $EXTRA_ARGS -- action \
          --close \
          "$PR_URL"
      if: |
        steps.pull_request.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
      run: |
        gh pr close \
          --delete-branch \
          "$PR_URL"
      if: |
        (steps.pull_request.outputs.method == 'sapling-pull-request' || steps.pull_request.outputs.method == 'github-pull-request') &&
        steps.command.outputs.continue == 'true'
