name: Close
description: Close a pull request
inputs:
  github-token:
    default: ${{ github.token }}
    description: The GitHub Token
    required: false
  pull-request-url:
    default: ${{ github.event.pull_request.html_url || github.event.issue.pull_request.html_url }}
    description: The Pull Request URL
    required: false
  registry:
    default: nixpkgs
    description: Nix registry to use
    required: false
  username:
    default: github-actions
    description: Username
    required: false
runs:
  using: composite
  steps:
    - id: stack
      uses: shikanime-studio/actions/stack@main
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-url: ${{ inputs.pull-request-url }}
    - if: runner.debug == '1'
      run: |
        echo "DEBUG_FLAG=--debug" >> "$GITHUB_ENV"
      shell: bash
    - env:
        GH_TOKEN: ${{ inputs.github-token }}
        USERNAME: ${{ inputs.username }}
      if: |
        steps.stack.outputs.method == 'ghstack'
      run: |
        GHSTACKRC_PATH=$(mktemp)
        cat > "$GHSTACKRC_PATH" <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = $GH_TOKEN
        github_username = $USERNAME
        EOF
        echo "GHSTACKRC_PATH=$GHSTACKRC_PATH" >> "$GITHUB_ENV"
      shell: bash
    - env:
        PR_URL: ${{ inputs.pull-request-url }}
        REGISTRY: ${{ inputs.registry }}
      if: |
        steps.stack.outputs.method == 'ghstack'
      run: |
        nix run "$REGISTRY#ghstack" -- $DEBUG_FLAG action \
          --close \
          "$PR_URL"
      shell: bash
    - env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
      if: |
        steps.stack.outputs.method == 'sapling-pull-request' ||
        steps.stack.outputs.method == 'github-pull-request'
      run: gh pr close --delete-branch "$PR_URL"
      shell: bash
