name: cleanup
description: Cleanup branches after Pull Request is closed
inputs:
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  head-ref:
    description: The head branch to delete
    required: false
    default: ${{ github.head_ref }}
  pull-request-url:
    description: The Pull Request URL
    required: true
runs:
  using: composite
  steps:
    - id: stack
      uses: shikanime-studio/actions/stack@main
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-url: ${{ inputs.pull-request-url }}
    - if: ${{ steps.stack.outputs.method == 'github-pull-request' }}
      env:
        HEAD_REF: ${{ inputs.head-ref }}
      run: git push origin --delete "$HEAD_REF" || true
      shell: bash
    - if: ${{ steps.stack.outputs.method == 'ghstack' }}
      env:
        HEAD_REF: ${{ inputs.head-ref }}
      run: |
        for role in base head orig; do
          git push origin --delete "${HEAD_REF%/head}/$role" || true
        done
      shell: bash
