name: land
description: Land pull request from a PR comment
inputs:
  base:
    description: The base branch to rebase onto
    required: false
    default: main
  email:
    description: Email
    required: false
    default: github-actions[bot]@users.noreply.github.com
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  fullname:
    description: Full name
    required: false
    default: github-actions[bot]
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  gpg-passphrase:
    description: GPG private key passphrase
    required: false
    default: ""
  gpg-private-key:
    description: GPG private key for signing commits
    required: false
    default: ""
  permissions:
    description: Permissions to require for the command
    required: false
    default: write,maintain,admin
  pull-request-url:
    description: The Pull Request URL
    required: false
    default: ${{ github.event.issue.pull_request.html_url }}
  reaction:
    description: Reaction to add to the triggering comment
    required: false
    default: rocket
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
  sign-commits:
    description: Set to true to sign commits with GPG
    required: false
    default: "false"
  username:
    description: Username
    required: false
    default: github-actions
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: .land
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
    - id: info
      uses: shikanime-studio/actions/stack@main
      if: steps.command.outputs.continue == 'true'
      with:
        pull-request-url: ${{ inputs.pull-request-url }}
        github-token: ${{ inputs.github-token }}
    - id: pull_request
      shell: bash
      env:
        PARAMS: ${{ steps.command.outputs.params }}
        INFO_METHOD: ${{ steps.info.outputs.method }}
      run: |
        METHOD=""

        if [ -n "$PARAMS" ]; then
          case "$PARAMS" in
            ghstack)
              METHOD="ghstack"
              ;;
            slpr)
              METHOD="sapling-pull-request"
              ;;
            ghpr)
              METHOD="github-pull-request"
              ;;
            *)
              echo "Unknown land method param '$PARAMS'. Expected 'ghstack', 'slpr' or 'ghpr'."
              exit 1
              ;;
          esac
        else
          METHOD="$INFO_METHOD"
        fi

        echo "method=$METHOD" >> "$GITHUB_OUTPUT"
      if: steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        EXTRA_ARGS: ${{ inputs.extra-args }}
        FULLNAME: ${{ inputs.fullname }}
        EMAIL: ${{ inputs.email }}
      run: |
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- config \
          --local ui.username "$FULLNAME <$EMAIL>"
      if: steps.command.outputs.continue == 'true'
    - id: importGPG
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
      if: |
        inputs.sign-commits == 'true' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        EXTRA_ARGS: ${{ inputs.extra-args }}
        GPG_KEY_ID: ${{ steps.importGPG.outputs.keyid }}
      run: |
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- config \
          --local gpg.key "$GPG_KEY_ID" \
          --local commit.gpgsign true
      if: |
        inputs.sign-commits == 'true' &&
        steps.pull_request.outputs.method == 'sapling-pull-request' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REGISTRY: ${{ inputs.registry }}
        EXTRA_ARGS: ${{ inputs.extra-args }}
        USERNAME: ${{ inputs.username }}
        PR_URL: ${{ inputs.pull-request-url }}
      run: |
        GHSTACKRC_PATH=$(mktemp)
        trap 'rm -f "$GHSTACKRC_PATH"' EXIT
        cat > "$GHSTACKRC_PATH" <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = $GH_TOKEN
        github_username = $USERNAME
        EOF

        nix run "$REGISTRY#ghstack" $EXTRA_ARGS -- land \
          "$PR_URL"
      if: |
        steps.pull_request.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REGISTRY: ${{ inputs.registry }}
        EXTRA_ARGS: ${{ inputs.extra-args }}
        PR_URL: ${{ inputs.pull-request-url }}
        BASE: ${{ inputs.base }}
      run: |
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- pr pull \
          --goto \
          "$PR_URL"
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- rebase \
          --dest "$BASE"
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- push \
          --to "$BASE"
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- push \
          --delete $(
            gh pr view \
              "$PR_URL" \
              --json headRefName \
              -q .headRefName
          )
      if: |
        steps.pull_request.outputs.method == 'sapling-pull-request' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
      run: |
        gh pr merge \
          --rebase \
          --delete-branch \
          "$PR_URL"
      if: |
        steps.pull_request.outputs.method == 'github-pull-request' &&
        steps.command.outputs.continue == 'true'
