name: ghstack
author: Shikanime Deva
branding:
  icon: globe
  color: gray-dark
description: Land a pull request
inputs:
  app-id:
    description: The GitHub App ID
    required: true
  private-key:
    description: The GitHub App private key
    required: true
  base:
    description: The base branch to rebase onto
    default: main
  reaction:
    description: The reaction to add
    default: rocket
  permissions:
    description: The permissions to check
    default: write,maintain,admin
  username:
    description: The username to use
    default: github-actions[bot]
  email:
    description: The email to use
    default: github-actions[bot]@users.noreply.github.com
  sign-commits:
    description: Set to true if the action should sign the commit with GPG
    default: "false"
  gpg-private-key:
    description: GPG Private Key with which to sign the commits in the PR to be created
    default: ""
  gpg-passphrase:
    description: GPG Private Key Passphrase for the GPG Private Key with which to sign the commits in the PR to be created
    default: ""
runs:
  using: composite
  steps:
    - id: createGithubAppToken
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - uses: github/command@v1
      id: commandLand
      with:
        command: .land
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: github/command@v1
      id: commandRebase
      with:
        command: .rebase
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: github/command@v1
      id: commandClose
      with:
        command: .close
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ steps.createGithubAppToken.outputs.token }}
        skip_ci: "true"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.createGithubAppToken.outputs.token }}
      if: |
        steps.commandLand.outputs.continue == 'true' ||
        steps.commandRebase.outputs.continue == 'true' ||
        steps.commandClose.outputs.continue == 'true'

    - uses: DeterminateSystems/nix-installer-action@v13
      if: |
        steps.commandLand.outputs.continue == 'true' ||
        steps.commandRebase.outputs.continue == 'true' ||
        steps.commandClose.outputs.continue == 'true'
    - uses: DeterminateSystems/magic-nix-cache-action@v8
      if: |
        steps.commandLand.outputs.continue == 'true' ||
        steps.commandRebase.outputs.continue == 'true' ||
        steps.commandClose.outputs.continue == 'true'

    - shell: bash
      run: |
        nix run nixpkgs#sapling -- config \
          --local ui.username "${{ inputs.username }}" \
          --local ui.email "${{ inputs.email }}"
      if: |
        steps.commandLand.outputs.continue == 'true' ||
        steps.commandRebase.outputs.continue == 'true' ||
        steps.commandClose.outputs.continue == 'true'
    - id: importGPG
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
      if: |
        inputs.sign-commits == 'true' && (
          steps.commandLand.outputs.continue == 'true' ||
          steps.commandRebase.outputs.continue == 'true' ||
          steps.commandClose.outputs.continue == 'true'
        )
    - shell: bash
      run: |
        nix run nixpkgs#sapling -- config \
          --local gpg.key "${{ steps.importGPG.outputs.keyid }}" \
          --local commit.gpgsign true
      if: |
        inputs.sign-commits == 'true' && (
          steps.commandLand.outputs.continue == 'true' ||
          steps.commandRebase.outputs.continue == 'true' ||
          steps.commandClose.outputs.continue == 'true'
        )

    - name: Land Pull Request
      shell: bash
      run: |
        if [ "${{ steps.commandLand.outputs.params }}" == "ghstack" ]; then
          nix run nixpkgs#sapling -- ghstack land \
            ${{ github.event.issue.pull_request.html_url }}
        elif [ "${{ steps.commandLand.outputs.params }}" == "pr" ]; then
          nix run nixpkgs#sapling -- pr pull |
            ${{ github.event.issue.pull_request.html_url }}
          nix run nixpkgs#sapling -- push --to ${{ inputs.base }}
        fi
      if: steps.commandLand.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ steps.createGithubAppToken.outputs.token }}

    - name: Rebase Pull Request
      shell: bash
      run: |
        nix run nixpkgs#sapling -- ghstack checkout \
          ${{ github.event.issue.pull_request.html_url }}
        nix run nixpkgs#sapling -- rebase \
          --dest ${{ inputs.base }}
        nix run nixpkgs#sapling -- ghstack submit
      if: steps.commandRebase.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ steps.createGithubAppToken.outputs.token }}

    - name: Close Pull Request
      shell: bash
      run: |
        nix run nixpkgs#sapling -- ghstack action \
          --close \
          ${{ github.event.issue.pull_request.html_url }}
      if: steps.commandClose.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ steps.createGithubAppToken.outputs.token }}
