name: sapling-action
author: Shikanime Studio
branding:
  icon: globe
  color: gray-dark
description: Land a pull request
inputs:
  base:
    description: The base branch to rebase onto
    default: main
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  gpg-passphrase:
    description: GPG Private Key Passphrase for the GPG Private Key with which to sign the commits in the PR to be created
    default: ""
  gpg-private-key:
    description: GPG Private Key with which to sign the commits in the PR to be created
    default: ""
  permissions:
    description: The permissions to check
    default: write,maintain,admin
  reaction:
    description: The reaction to add
    default: rocket
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
  sign-commits:
    description: Set to true if the action should sign the commit with GPG
    default: "false"
  username:
    description: The username to use
    default: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: commandLand
      with:
        command: .land
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
    - uses: github/command@v1
      id: commandRebase
      with:
        command: .rebase
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
        skip_ci: true
    - uses: github/command@v1
      id: commandClose
      with:
        command: .close
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
        skip_ci: true

    - shell: bash
      run: |
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- config \
          --local ui.username "${{ inputs.username }}"
      if: |
        steps.commandLand.outputs.continue == 'true' ||
        steps.commandRebase.outputs.continue == 'true' ||
        steps.commandClose.outputs.continue == 'true'
    - id: importGPG
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
      if: |
        inputs.sign-commits == 'true' && (
          steps.commandLand.outputs.continue == 'true' ||
          steps.commandRebase.outputs.continue == 'true' ||
          steps.commandClose.outputs.continue == 'true'
        )
    - shell: bash
      run: |
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- config \
          --local gpg.key "${{ steps.importGPG.outputs.keyid }}" \
          --local commit.gpgsign true
      if: |
        inputs.sign-commits == 'true' && (
          steps.commandLand.outputs.continue == 'true' ||
          steps.commandRebase.outputs.continue == 'true' ||
          steps.commandClose.outputs.continue == 'true'
        )
    - shell: bash
      run: |
    - shell: bash
      run: |
        cat > ~/.ghstackrc <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = ${{ inputs.github-token }}
        github_username = shikanime
        EOF
      if: |
        steps.commandLand.outputs.params != 'pr' && (
          steps.commandLand.outputs.continue == 'true' ||
          steps.commandRebase.outputs.continue == 'true' ||
          steps.commandClose.outputs.continue == 'true'
        )

    - name: Land Pull Request
      shell: bash
      run: |
        if [ "${{ steps.commandLand.outputs.params }}" == "ghstack" ] || \
           [ -z "${{ steps.commandLand.outputs.params }}" ]; then
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- rebase \
            --dest ${{ inputs.base }}
          nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- land \
            ${{ github.event.issue.pull_request.html_url }}
        elif [ "${{ steps.commandLand.outputs.params }}" == "pr" ]; then
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr pull \
            --goto \
            ${{ github.event.issue.pull_request.html_url }}
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- rebase \
            --dest ${{ inputs.base }}
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- push \
            --to ${{ inputs.base }}
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- push \
            --delete $(
              gh pr view \
                ${{ github.event.issue.pull_request.html_url }} \
                --json headRefName \
                -q .headRefName
            )
        fi
      if: steps.commandLand.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Rebase Pull Request
      shell: bash
      run: |
        if [ "${{ steps.commandRebase.outputs.params }}" == "ghstack" ] || \
           [ -z "${{ steps.commandRebase.outputs.params }}" ]; then
          nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- checkout \
            ${{ github.event.issue.pull_request.html_url }}
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- rebase \
            --dest ${{ inputs.base }}
          nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- submit
        elif [ "${{ steps.commandRebase.outputs.params }}" == "pr" ]; then
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr checkout \
            --goto \
            ${{ github.event.issue.pull_request.html_url }}
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- rebase \
            --dest ${{ inputs.base }}
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr submit
        fi
      if: steps.commandRebase.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Close Pull Request
      shell: bash
      run: |
        if [ "${{ steps.commandClose.outputs.params }}" == "ghstack" ] || \
           [ -z "${{ steps.commandClose.outputs.params }}" ]; then
          nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- action \
            --close \
            ${{ github.event.issue.pull_request.html_url }}
        elif [ "${{ steps.commandClose.outputs.params }}" == "pr" ]; then
          gh pr close \
            --delete-branch \
            ${{ github.event.issue.pull_request.html_url }}
        fi
      if: steps.commandClose.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
