name: ghstack
author: Shikanime Deva
branding:
  icon: globe
  color: gray-dark
description: Land a pull request
inputs:
  appId:
    description: The GitHub App ID
    required: true
  privateKey:
    description: The GitHub App private key
    required: true
  base:
    description: The base branch to rebase onto
    default: main
  reaction:
    description: The reaction to add
    default: rocket
  permissions:
    description: The permissions to check
    default: write,maintain,admin
  username:
    description: The username to use
    default: github-actions[bot]
  email:
    description: The email to use
    default: github-actions[bot]@users.noreply.github.com
runs:
  using: composite
  steps:
    - id: createGithubAppToken
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.appId }}
        private-key: ${{ inputs.privateKey }}
    - uses: .github/actions/ghstack.yml
      with:
        command: .ghstack
        reaction: ${{ inputs.reaction }}
        permissions: ${{ inputs.permissions }}
        username: ${{ inputs.username }}
        email: ${{ inputs.email }}
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: .github/actions/rebase.yml
      with:
        base: ${{ inputs.base }}
        command: .rebase
        reaction: ${{ inputs.reaction }}
        permissions: ${{ inputs.permissions }}
        username: ${{ inputs.username }}
        email: ${{ inputs.email }}
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: .github/actions/pr.yml
      with:
        command: .pr
        reaction: ${{ inputs.reaction }}
        permissions: ${{ inputs.permissions }}
        username: ${{ inputs.username }}
        email: ${{ inputs.email }}
        token: ${{ steps.createGithubAppToken.outputs.token }}
