name: ghstack
author: Shikanime Deva
branding:
  icon: globe
  color: gray-dark
description: Land a pull request
inputs:
  appId:
    description: The GitHub App ID
    required: true
  privateKey:
    description: The GitHub App private key
    required: true
  owner:
    description: The owner of the repository
    default: ${{ github.repository_owner }}
  repositories:
    description: The repositories to grant access to
    default: ${{ github.repository }}
  command:
    description: The command to run
    default: ".ghstack"
  reaction:
    description: The reaction to add
    default: "rocket"
  permissions:
    description: The permissions to check
    default: "write,maintain,admin"
  username:
    description: The username to use
    default: "github-actions[bot]"
  email:
    description: The email to use
    default: "github-actions[bot]@users.noreply.github.com"
runs:
  using: composite
  steps:
    - id: createGithubAppToken
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.appId }}
        private-key: ${{ inputs.privateKey }}
        owner: ${{ inputs.owner }}
        repositories: ${{ inputs.repositories }}
    - uses: github/command@v1
      id: command
      with:
        command: ${{ inputs.command }}
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: DeterminateSystems/nix-installer-action@v13
      if: ${{ steps.command.outputs.continue == 'true' }}
    - uses: DeterminateSystems/magic-nix-cache-action@v8
      if: ${{ steps.command.outputs.continue == 'true' }}
    - name: Land Pull Request
      shell: bash
      run: |
        nix run nixpkgs#sapling -- config \
          --local ui.username "${{ inputs.username }}" \
          --local ui.email "${{ inputs.email }}"
        nix run nixpkgs#sapling -- ghstack land \
          ${{ github.event.issue.pull_request.html_url }}
      if: ${{ steps.command.outputs.continue == 'true' }}
      env:
        GH_TOKEN: ${{ steps.createGithubAppToken.outputs.token }}
