name: rebase
description: Rebase pull request from a PR comment
inputs:
  base:
    description: The base branch to rebase onto
    required: false
    default: main
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  ghstack-username:
    description: Ghstack username
    required: false
    default: github-actions
  gpg-passphrase:
    description: GPG private key passphrase
    required: false
    default: ""
  gpg-private-key:
    description: GPG private key for signing commits
    required: false
    default: ""
  permissions:
    description: Permissions to require for the command
    required: false
    default: write,maintain,admin
  reaction:
    description: Reaction to add to the triggering comment
    required: false
    default: rocket
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
  sign-commits:
    description: Set to true to sign commits with GPG
    required: false
    default: "false"
  username:
    description: Sapling username to configure
    required: false
    default: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: .rebase
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
        skip_ci: true
    - shell: bash
      run: |
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- config \
          --local ui.username "${{ inputs.username }}"
      if: steps.command.outputs.continue == 'true'
    - id: importGPG
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
      if: |
        inputs.sign-commits == 'true' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      run: |
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- config \
          --local gpg.key "${{ steps.importGPG.outputs.keyid }}" \
          --local commit.gpgsign true
      if: |
        inputs.sign-commits == 'true' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      run: |
        cat > ~/.ghstackrc <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = ${{ inputs.github-token }}
        github_username = ${{ inputs.ghstack-username }}
        EOF
      if: |
        steps.command.outputs.params != 'pr' &&
        steps.command.outputs.continue == 'true'
    - name: Rebase Pull Request
      shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        PARAMS="${{ steps.command.outputs.params }}"
        BRANCH=$(gh pr view "$PR_URL" --json headRefName -q .headRefName)

        MODE=""

        if [ -n "$PARAMS" ]; then
          case "$PARAMS" in
            ghstack)
              MODE="ghstack"
              ;;
            slpr)
              MODE="slpr"
              ;;
            ghpr)
              MODE="ghpr"
              ;;
            *)
              MODE="$PARAMS"
              ;;
          esac
        else
          if [[ "$BRANCH" == gh/* ]]; then
            MODE="ghstack"
          elif [[ "$BRANCH" =~ ^pr[0-9]+$ ]]; then
            MODE="slpr"
          else
            MODE="ghpr"
          fi
        fi

        if [ "$MODE" = "ghstack" ]; then
          nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- checkout \
            "$PR_URL"
          nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- submit
        elif [ "$MODE" = "slpr" ]; then
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr checkout \
            --goto \
            "$PR_URL"
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- rebase \
            --dest ${{ inputs.base }}
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr submit
        elif [ "$MODE" = "ghpr" ]; then
          echo "GitHub CLI fallback for rebase is not implemented; use 'ghstack' or 'slpr' modes explicitly."
          exit 1
        else
          echo "Unknown rebase mode: '$MODE'. Expected ghstack, slpr, or ghpr."
          exit 1
        fi
      if: steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
