name: Setup Nix
description: Install Nix and configure Cachix
inputs:
  github-token:
    default: ${{ github.token }}
    description: GitHub token used by the Nix installer
    required: false
  cachix-name:
    default: ""
    description: Cachix cache name
    required: false
  cachix-auth-token:
    default: ""
    description: Cachix auth token
    required: false
  cachix-signing-key:
    default: ""
    description: Cachix signing key
    required: false
  extra-config:
    default: ""
    description: Extra Nix config
    required: false
  extra-platforms:
    default: ""
    description: Platforms to setup QEMU for
    required: false
runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@v4
      if: ${{ inputs.extra-platforms != '' }}
      with:
        platforms: ${{ inputs.extra-platforms }}
    - id: extra-platforms-config
      uses: actions/github-script@v8
      if: ${{ inputs.extra-platforms != '' }}
      with:
        script: |
          const raw = core.getInput('extra-platforms') || '';
          const extraPlatformsConfig = raw
            .split(',')
            .map((p) => p.trim())
            .filter((p) => p)
            .map((p) => {
              switch (p) {
              case 'amd64':
                return 'x86_64-linux';
              case 'arm64':
                return 'aarch64-linux';
              default:
                core.warning(`unsupported platform: ${p}`);
                return null;
              }
            })
            .filter((p) => p)
            .join(' ');
          if (extraPlatformsConfig) {
            core.setOutput('nix-config', `extra-platforms = ${extraPlatformsConfig}`);
          }
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          ${{ steps.extra-platforms-config.outputs.nix-config }}
          ${{ inputs.extra-config }}
        github_access_token: ${{ inputs.github-token }}
    - if: ${{ inputs.cachix-name != '' }}
      uses: cachix/cachix-action@v17
      with:
        authToken: ${{ inputs.cachix-auth-token }}
        name: ${{ inputs.cachix-name }}
        signingKey: ${{ inputs.cachix-signing-key }}
