name: Setup Nix
description: Install Nix and configure Cachix
inputs:
  github-token:
    default: ${{ github.token }}
    description: GitHub token used by the Nix installer
    required: false
  cachix-name:
    default: ""
    description: Cachix cache name
    required: false
  cachix-auth-token:
    default: ""
    description: Cachix auth token
    required: false
  cachix-signing-key:
    default: ""
    description: Cachix signing key
    required: false
  extra-config:
    default: ""
    description: Extra Nix config
    required: false
  extra-platforms:
    default: ""
    description: Platforms to setup QEMU for
    required: false
runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@v4
      if: ${{ inputs.extra-platforms != '' }}
      with:
        platforms: ${{ inputs.extra-platforms }}
    - id: extra-platforms-config
      if: ${{ inputs.extra-platforms != '' }}
      env:
        EXTRA_PLATFORMS: ${{ inputs.extra-platforms }}
      shell: bash
      run: |
        NIX_PLATFORMS=""

        IFS=',' read -ra parts <<<"$EXTRA_PLATFORMS"
        for part in "${parts[@]}"; do
          p="$(echo "$part" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
          if [ -z "$p" ]; then
            continue
          fi

          case "$p" in
            amd64)
              NIX_PLATFORMS="${NIX_PLATFORMS} x86_64-linux"
              ;;
            arm64)
              NIX_PLATFORMS="${NIX_PLATFORMS} aarch64-linux"
              ;;
            *)
              echo "::warning::unsupported platform: ${p}"
              ;;
          esac
        done

        NIX_PLATFORMS="$(echo "$NIX_PLATFORMS" | xargs)"
        if [[ -n "$NIX_PLATFORMS" ]]; then
          echo "nix-config=extra-platforms = ${NIX_PLATFORMS}" >> "$GITHUB_OUTPUT"
        fi
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          ${{ steps.extra-platforms-config.outputs.nix-config }}
          ${{ inputs.extra-config }}
        github_access_token: ${{ inputs.github-token }}
    - if: ${{ inputs.cachix-name != '' }}
      uses: cachix/cachix-action@v17
      with:
        authToken: ${{ inputs.cachix-auth-token }}
        name: ${{ inputs.cachix-name }}
        signingKey: ${{ inputs.cachix-signing-key }}
