name: ghstack
description: Land Pull Requests with ghstack
inputs:
  command:
    description: The command to run
    required: true
  reaction:
    description: The reaction to add
    required: true
  permissions:
    description: The permissions to check
    required: true
  token:
    description: The GitHub token to use
    required: true
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: ${{ inputs.command }}
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.token }}
    - name: Land Pull Request
      shell: bash
      run: |
        nix run nixpkgs#sapling -- ghstack land \
          ${{ github.event.issue.pull_request.html_url }}
      if: ${{ steps.command.outputs.continue == 'true' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
