name: Rebase
description: Rebase Pull Requests with ghstack
inputs:
  base:
    description: The base branch to rebase onto
    required: true
  command:
    description: The command to run
    required: true
  reaction:
    description: The reaction to add
    required: true
  permissions:
    description: The permissions to check
    required: true
  token:
    description: The GitHub token to use
    required: true
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: ${{ inputs.command }}
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.token }}
    - name: Land Pull Request
      shell: bash
      run: |
        nix run nixpkgs#sapling -- ghstack checkout \
          ${{ github.event.issue.pull_request.html_url }}
        nix run nixpkgs#sapling -- rebase \
          --dest ${{ inputs.base }}
        nix run nixpkgs#sapling -- ghstack submit
      if: ${{ steps.command.outputs.continue == 'true' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
