name: backport
description: Backport pull request from a PR comment
inputs:
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  gpg-passphrase:
    description: GPG private key passphrase
    required: false
    default: ""
  gpg-private-key:
    description: GPG private key for signing commits
    required: false
    default: ""
  permissions:
    description: Permissions to require for the command
    required: false
    default: write,maintain,admin
  reaction:
    description: Reaction to add to the triggering comment
    required: false
    default: rocket
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
  sign-commits:
    description: Set to true to sign commits with GPG
    required: false
    default: "false"
  username:
    description: Username for ghstack and jj
    required: false
    default: github-actions
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: .backport
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
        skip_ci: true
    - id: pull_request
      shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        BRANCH=$(gh pr view "$PR_URL" --json headRefName -q .headRefName)

        METHOD=""

        if [[ "$BRANCH" =~ ^gh/[^/]+/[0-9]+/head$ ]]; then
          METHOD="ghstack"
        elif [[ "$BRANCH" =~ ^pr[0-9]+$ ]]; then
          METHOD="slpr"
        else
          METHOD="ghpr"
        fi

        echo "method=$METHOD" >> "$GITHUB_OUTPUT"
      if: steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - id: importGPG
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
      if: |
        inputs.sign-commits == 'true' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        TARGET_BRANCH="${{ steps.command.outputs.params }}"

        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        cat > ~/.ghstackrc <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = ${{ inputs.github-token }}
        github_username = ${{ inputs.username }}
        EOF

        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- checkout \
          "$PR_URL"
        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- unlink
        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- rebase \
          --dest "$TARGET_BRANCH"
        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- submit
      if: |
        steps.pull_request.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        TARGET_BRANCH="${{ steps.command.outputs.params }}"

        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr pull \
          --goto \
          "$PR_URL"
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr unlink
        if [ "${{ inputs.sign-commits }}" = "true" ]; then
          nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- config \
            --local gpg.key "${{ steps.importGPG.outputs.keyid }}" \
            --local commit.gpgsign true
        fi
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- rebase \
          --dest "$TARGET_BRANCH"
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr submit
      if: |
        steps.pull_request.outputs.method == 'slpr' &&
        steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        TARGET_BRANCH="${{ steps.command.outputs.params }}"

        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "${{ inputs.registry }}#jujutsu" ${{ inputs.extra-args }} -- git init \
          --git-repo . \
          --colocate || true
        nix run "${{ inputs.registry }}#jujutsu" ${{ inputs.extra-args }} -- git fetch \
          --remote origin

        nix run "${{ inputs.registry }}#jujutsu" ${{ inputs.extra-args }} -- config set \
          --repo templates.git_push_bookmark \
          "\"${{ inputs.username }}/push-\" ++ change_id.short()"

        nix run "${{ inputs.registry }}#jujutsu" ${{ inputs.extra-args }} -- new \
          "$TARGET_BRANCH@origin"
        nix run "${{ inputs.registry }}#jujutsu" ${{ inputs.extra-args }} -- rebase \
          -b @ \
          -o "$PR_URL"
        nix run "${{ inputs.registry }}#jujutsu" ${{ inputs.extra-args }} -- git push \
          --change @

        PUSH_BRANCH=$(nix run "${{ inputs.registry }}#jujutsu" ${{ inputs.extra-args }} -- log \
          --limit 1 \
          --template "{{bookmarks}}" \
          @)

        ORIG_TITLE=$(gh pr view "$PR_URL" --json title -q .title)
        ORIG_BODY_FILE=<(gh pr view "$PR_URL" --json body -q .body)

        gh pr create \
          --head "$PUSH_BRANCH" \
          --base "$TARGET_BRANCH" \
          --title "$ORIG_TITLE" \
          --body-file "$ORIG_BODY_FILE"
      if: |
        steps.pull_request.outputs.method == 'ghpr' &&
        steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
