name: backport
description: Backport pull request from a PR comment
inputs:
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  ghstack-username:
    description: Ghstack username
    required: false
    default: github-actions
  permissions:
    description: Permissions to require for the command
    required: false
    default: write,maintain,admin
  reaction:
    description: Reaction to add to the triggering comment
    required: false
    default: rocket
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: .backport
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
        skip_ci: true
    - id: pull_request
      shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        BRANCH=$(gh pr view "$PR_URL" --json headRefName -q .headRefName)

        METHOD=""

        if [[ "$BRANCH" == gh/* ]]; then
          METHOD="ghstack"
        elif [[ "$BRANCH" =~ ^pr[0-9]+$ ]]; then
          METHOD="slpr"
        else
          echo "Unable to determine backport method from branch '$BRANCH'. Follow naming gh/* or prNN."
          exit 1
        fi

        echo "method=$METHOD" >> "$GITHUB_OUTPUT"
      if: steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - shell: bash
      run: |
        cat > ~/.ghstackrc <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = ${{ inputs.github-token }}
        github_username = ${{ inputs.ghstack-username }}
        EOF
      if: |
        steps.pull_request.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        TARGET_BRANCH="${{ steps.command.outputs.params }}"

        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- checkout \
          "$PR_URL"
        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- unlink
        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- rebase \
          --dest "$TARGET_BRANCH"
        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- submit
      if: |
        steps.pull_request.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        TARGET_BRANCH="${{ steps.command.outputs.params }}"

        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr pull \
          --goto \
          "$PR_URL"
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr unlink
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- rebase \
          --dest "$TARGET_BRANCH"
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr submit
      if: |
        steps.pull_request.outputs.method == 'slpr' &&
        steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
