name: backport
description: Backport pull request from a PR comment
inputs:
  github-token:
    default: ${{ github.token }}
    description: The GitHub Token
    required: false
  gpg-passphrase:
    default: ""
    description: GPG private key passphrase
    required: false
  gpg-private-key:
    default: ""
    description: GPG private key for signing commits
    required: false
  permissions:
    default: write,maintain,admin
    description: Permissions to require for the command
    required: false
  pull-request-url:
    default: ${{ github.event.issue.pull_request.html_url }}
    description: The Pull Request URL
    required: false
  reaction:
    default: rocket
    description: Reaction to add to the triggering comment
    required: false
  registry:
    default: nixpkgs
    description: Nix registry to use
    required: false
  sign-commits:
    default: "false"
    description: Set to true to sign commits with GPG
    required: false
  username:
    default: github-actions
    description: Username
    required: false
runs:
  using: composite
  steps:
    - id: command
      uses: github/command@v1
      with:
        allowed_contexts: pull_request
        command: .backport
        github_token: ${{ inputs.github-token }}
        permissions: ${{ inputs.permissions }}
        reaction: ${{ inputs.reaction }}
        skip_ci: true
    - id: stack
      if: steps.command.outputs.continue == 'true'
      uses: shikanime-studio/actions/stack@main
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-url: ${{ inputs.pull-request-url }}
    - if: steps.command.outputs.continue == 'true' && runner.debug == '1'
      run: |
        echo "EXTRA_FLAGS=--debug" >> "$GITHUB_ENV"
      shell: bash
    - id: importGPG
      if: |
        inputs.sign-commits == 'true' &&
        steps.command.outputs.continue == 'true'
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
    - env:
        GPG_KEY_ID: ${{ steps.importGPG.outputs.keyid }}
        REGISTRY: ${{ inputs.registry }}
      if: |
        inputs.sign-commits == 'true' &&
        steps.stack.outputs.method == 'sapling-pull-request' &&
        steps.command.outputs.continue == 'true'
      run: |
        nix run "$REGISTRY#sapling" -- config \
          --local gpg.key "$GPG_KEY_ID" \
          --local commit.gpgsign true $EXTRA_FLAGS
      shell: bash
    - env:
        GH_TOKEN: ${{ inputs.github-token }}
        USERNAME: ${{ inputs.username }}
      if: |
        steps.stack.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
      run: |
        GHSTACKRC_PATH=$(mktemp)
        cat > "$GHSTACKRC_PATH" <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = $GH_TOKEN
        github_username = $USERNAME
        EOF
        echo "GHSTACKRC_PATH=$GHSTACKRC_PATH" >> "$GITHUB_ENV"
      shell: bash
    - env:
        PR_URL: ${{ inputs.pull-request-url }}
        REGISTRY: ${{ inputs.registry }}
        TARGET_BRANCH: ${{ steps.command.outputs.params }}
      if: |
        steps.stack.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
      run: |
        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "$REGISTRY#ghstack" -- $EXTRA_FLAGS checkout "$PR_URL"
        nix run "$REGISTRY#ghstack" -- $EXTRA_FLAGS unlink "$PR_URL"
        git fetch origin "$TARGET_BRANCH"
        git rebase "origin/$TARGET_BRANCH"
        nix run "$REGISTRY#ghstack" -- $EXTRA_FLAGS submit
      shell: bash
    - env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
        REGISTRY: ${{ inputs.registry }}
        TARGET_BRANCH: ${{ steps.command.outputs.params }}
      if: |
        steps.stack.outputs.method == 'sapling-pull-request' &&
        steps.command.outputs.continue == 'true'
      run: |
        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "$REGISTRY#sapling" -- pr pull \
          --goto \
          "$PR_URL" $EXTRA_FLAGS
        nix run "$REGISTRY#sapling" -- pr \
          unlink $EXTRA_FLAGS
        nix run "$REGISTRY#sapling" -- rebase \
          --dest "$TARGET_BRANCH" $EXTRA_FLAGS
        nix run "$REGISTRY#sapling" -- pr \
          submit $EXTRA_FLAGS
      shell: bash
    - env:
        GPG_KEY_ID: ${{ steps.importGPG.outputs.keyid }}
        REGISTRY: ${{ inputs.registry }}
      if: |
        inputs.sign-commits == 'true' &&
        steps.stack.outputs.method == 'github-pull-request' &&
        steps.command.outputs.continue == 'true'
      run: |
        nix run "$REGISTRY#jujutsu" -- config set \
          --repo signing.backend gpg $EXTRA_FLAGS
        nix run "$REGISTRY#jujutsu" -- config set \
          --repo signing.sign-all true $EXTRA_FLAGS
        nix run "$REGISTRY#jujutsu" -- config set \
          --repo signing.key "$GPG_KEY_ID" $EXTRA_FLAGS
      shell: bash
    - continue-on-error: true
      env:
        REGISTRY: ${{ inputs.registry }}
      if: |
        steps.stack.outputs.method == 'github-pull-request' &&
        steps.command.outputs.continue == 'true'
      run: |
        nix run "$REGISTRY#jujutsu" -- git \
          init $EXTRA_FLAGS
      shell: bash
    - env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
        REGISTRY: ${{ inputs.registry }}
        TARGET_BRANCH: ${{ steps.command.outputs.params }}
        USERNAME: ${{ inputs.username }}
      if: |
        steps.stack.outputs.method == 'github-pull-request' &&
        steps.command.outputs.continue == 'true'
      run: |
        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "$REGISTRY#jujutsu" -- git fetch \
          --remote origin $EXTRA_FLAGS

        nix run "$REGISTRY#jujutsu" -- config set \
          --repo templates.git_push_bookmark \
          "\"$USERNAME/push-\" ++ change_id.short()" $EXTRA_FLAGS

        nix run "$REGISTRY#jujutsu" -- new \
          "$TARGET_BRANCH@origin" $EXTRA_FLAGS
        nix run "$REGISTRY#jujutsu" -- rebase \
          -b @ \
          -o "$PR_URL" $EXTRA_FLAGS
        nix run "$REGISTRY#jujutsu" -- git push \
          --change @ $EXTRA_FLAGS

        PUSH_BRANCH=$(nix run "$REGISTRY#jujutsu" -- log \
          --limit 1 \
          --template "{{bookmarks}}" \
          @ $EXTRA_FLAGS)

        ORIG_TITLE=$(gh pr view "$PR_URL" --json title -q .title)
        ORIG_BODY_FILE=<(gh pr view "$PR_URL" --json body -q .body)

        gh pr create \
          --head "$PUSH_BRANCH" \
          --base "$TARGET_BRANCH" \
          --title "$ORIG_TITLE" \
          --body-file "$ORIG_BODY_FILE"
      shell: bash
