name: backport
description: Backport pull request from a PR comment
inputs:
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  gpg-passphrase:
    description: GPG private key passphrase
    required: false
    default: ""
  gpg-private-key:
    description: GPG private key for signing commits
    required: false
    default: ""
  permissions:
    description: Permissions to require for the command
    required: false
    default: write,maintain,admin
  pull-request-url:
    description: The Pull Request URL
    required: false
    default: ${{ github.event.issue.pull_request.html_url }}
  reaction:
    description: Reaction to add to the triggering comment
    required: false
    default: rocket
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
  sign-commits:
    description: Set to true to sign commits with GPG
    required: false
    default: "false"
  username:
    description: Username
    required: false
    default: github-actions
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: .backport
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
        skip_ci: true
    - id: stack
      uses: shikanime-studio/actions/stack@main
      if: steps.command.outputs.continue == 'true'
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-url: ${{ inputs.pull-request-url }}
    - id: importGPG
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
      if: |
        inputs.sign-commits == 'true' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        EXTRA_ARGS: ${{ inputs.extra-args }}
        GPG_KEY_ID: ${{ steps.importGPG.outputs.keyid }}
        REGISTRY: ${{ inputs.registry }}
      run: |
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- config \
          --local gpg.key "$GPG_KEY_ID" \
          --local commit.gpgsign true
      if: |
        inputs.sign-commits == 'true' &&
        steps.stack.outputs.method == 'sapling-pull-request' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        EXTRA_ARGS: ${{ inputs.extra-args }}
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
        REGISTRY: ${{ inputs.registry }}
        TARGET_BRANCH: ${{ steps.command.outputs.params }}
        USERNAME: ${{ inputs.username }}
      run: |
        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        GHSTACKRC_PATH=$(mktemp)
        trap 'rm -f "$GHSTACKRC_PATH"' EXIT
        cat > "$GHSTACKRC_PATH" <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = $GH_TOKEN
        github_username = $USERNAME
        EOF

        nix run "$REGISTRY#ghstack" $EXTRA_ARGS -- checkout \
          "$PR_URL"
        nix run "$REGISTRY#ghstack" $EXTRA_ARGS -- unlink
        nix run "$REGISTRY#ghstack" $EXTRA_ARGS -- rebase \
          --dest "$TARGET_BRANCH"
        nix run "$REGISTRY#ghstack" $EXTRA_ARGS -- submit
      if: |
        steps.stack.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        EXTRA_ARGS: ${{ inputs.extra-args }}
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
        REGISTRY: ${{ inputs.registry }}
        TARGET_BRANCH: ${{ steps.command.outputs.params }}
      run: |
        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- pr pull \
          --goto \
          "$PR_URL"
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- pr unlink
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- rebase \
          --dest "$TARGET_BRANCH"
        nix run "$REGISTRY#sapling" $EXTRA_ARGS -- pr submit
      if: |
        steps.stack.outputs.method == 'sapling-pull-request' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        EXTRA_ARGS: ${{ inputs.extra-args }}
        GPG_KEY_ID: ${{ steps.importGPG.outputs.keyid }}
        REGISTRY: ${{ inputs.registry }}
      run: |
        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- config set \
          --repo signing.backend gpg
        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- config set \
          --repo signing.sign-all true
        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- config set \
          --repo signing.key "$GPG_KEY_ID"
      if: |
        inputs.sign-commits == 'true' &&
        steps.stack.outputs.method == 'github-pull-request' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      continue-on-error: true
      env:
        EXTRA_ARGS: ${{ inputs.extra-args }}
        REGISTRY: ${{ inputs.registry }}
      run: |
        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- git init \
          --git-repo . \
          --colocate
      if: |
        steps.stack.outputs.method == 'github-pull-request' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      env:
        EXTRA_ARGS: ${{ inputs.extra-args }}
        GH_TOKEN: ${{ inputs.github-token }}
        PR_URL: ${{ inputs.pull-request-url }}
        REGISTRY: ${{ inputs.registry }}
        TARGET_BRANCH: ${{ steps.command.outputs.params }}
        USERNAME: ${{ inputs.username }}
      run: |
        if [ -z "$TARGET_BRANCH" ]; then
          echo "Error: backport target branch is required, e.g. '.backport | release-1.0'"
          exit 1
        fi

        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- git fetch \
          --remote origin

        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- config set \
          --repo templates.git_push_bookmark \
          "\"$USERNAME/push-\" ++ change_id.short()"

        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- new \
          "$TARGET_BRANCH@origin"
        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- rebase \
          -b @ \
          -o "$PR_URL"
        nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- git push \
          --change @

        PUSH_BRANCH=$(nix run "$REGISTRY#jujutsu" $EXTRA_ARGS -- log \
          --limit 1 \
          --template "{{bookmarks}}" \
          @)

        ORIG_TITLE=$(gh pr view "$PR_URL" --json title -q .title)
        ORIG_BODY_FILE=<(gh pr view "$PR_URL" --json body -q .body)

        gh pr create \
          --head "$PUSH_BRANCH" \
          --base "$TARGET_BRANCH" \
          --title "$ORIG_TITLE" \
          --body-file "$ORIG_BODY_FILE"
      if: |
        steps.stack.outputs.method == 'github-pull-request' &&
        steps.command.outputs.continue == 'true'
