name: rebase
description: Rebase pull request from a PR comment
inputs:
  base:
    description: The base branch to rebase onto
    required: false
    default: main
  email:
    description: Email
    required: false
    default: github-actions[bot]@users.noreply.github.com
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  fullname:
    description: Full name
    required: false
    default: github-actions[bot]
  github-token:
    description: The GitHub Token
    required: false
    default: ${{ github.token }}
  gpg-passphrase:
    description: GPG private key passphrase
    required: false
    default: ""
  gpg-private-key:
    description: GPG private key for signing commits
    required: false
    default: ""
  permissions:
    description: Permissions to require for the command
    required: false
    default: write,maintain,admin
  reaction:
    description: Reaction to add to the triggering comment
    required: false
    default: rocket
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
  sign-commits:
    description: Set to true to sign commits with GPG
    required: false
    default: "false"
  username:
    description: Username
    required: false
    default: github-actions
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: .rebase
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.github-token }}
        skip_ci: true
    - id: pull_request
      shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        PARAMS="${{ steps.command.outputs.params }}"
        BRANCH=$(gh pr view "$PR_URL" --json headRefName -q .headRefName)

        METHOD=""

        if [ -n "$PARAMS" ]; then
          case "$PARAMS" in
            ghstack)
              METHOD="ghstack"
              ;;
            slpr)
              METHOD="slpr"
              ;;
            ghpr)
              METHOD="ghpr"
              ;;
            *)
              echo "Unknown rebase method param '$PARAMS'. Expected 'ghstack', 'slpr' or 'ghpr'."
              exit 1
              ;;
          esac
        else
          if [[ "$BRANCH" =~ ^gh/[^/]+/[0-9]+/head$ ]]; then
            METHOD="ghstack"
          elif [[ "$BRANCH" =~ ^pr[0-9]+$ ]]; then
            METHOD="slpr"
          else
            METHOD="ghpr"
          fi
        fi

        echo "method=$METHOD" >> "$GITHUB_OUTPUT"
      if: steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - shell: bash
      run: |
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- config \
          --local ui.username "${{ inputs.fullname }} <${{ inputs.email }}>"
      if: steps.command.outputs.continue == 'true'
    - id: importGPG
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
      if: |
        inputs.sign-commits == 'true' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      run: |
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- config \
          --local gpg.key "${{ steps.importGPG.outputs.keyid }}" \
          --local commit.gpgsign true
      if: |
        inputs.sign-commits == 'true' &&
        steps.pull_request.outputs.method == 'slpr' &&
        steps.command.outputs.continue == 'true'
    - shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"

        cat > ~/.ghstackrc <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = ${{ inputs.github-token }}
        github_username = ${{ inputs.username }}
        EOF

        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- checkout \
          "$PR_URL"
        git fetch origin "${{ inputs.base }}"
        git rebase "origin/${{ inputs.base }}"
        nix run "${{ inputs.registry }}#ghstack" ${{ inputs.extra-args }} -- submit
      if: |
        steps.pull_request.outputs.method == 'ghstack' &&
        steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"

        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr checkout \
          --goto \
          "$PR_URL"
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- rebase \
          --dest ${{ inputs.base }}
        nix run "${{ inputs.registry }}#sapling" ${{ inputs.extra-args }} -- pr submit
      if: |
        steps.pull_request.outputs.method == 'slpr' &&
        steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.html_url }}"
        BASE_BRANCH=$(gh pr view "$PR_URL" --json baseRefName -q .baseRefName)

        git fetch origin
        gh pr checkout "$PR_URL"
        git rebase "origin/$BASE_BRANCH"
        git push --force-with-lease
      if: |
        steps.pull_request.outputs.method == 'ghpr' &&
        steps.command.outputs.continue == 'true'
      env:
        GH_TOKEN: ${{ inputs.github-token }}
