name: update
author: Shikanime Studio
branding:
  color: gray-dark
  icon: globe
description: Update Nix flake and land changes
inputs:
  base:
    default: main
    description: The base branch to create or update against
    required: false
  commit-message:
    default: Update Flake
    description: Commit message
    required: false
  email:
    default: github-actions[bot]@users.noreply.github.com
    description: Email
  fullname:
    default: github-actions[bot]
    description: Full name
    required: false
  github-token:
    default: ${{ github.token }}
    description: The GitHub Token
    required: false
  gpg-passphrase:
    default: ""
    description: GPG Private Key Passphrase for the GPG Private Key with which to sign the commits in the PR to be created
  gpg-private-key:
    default: ""
    description: GPG Private Key with which to sign the commits in the PR to be created
  method:
    default: ghstack
    description: Publication method, one of 'ghstack', 'sapling-pull-request' or 'github-pull-request'
    required: false
  registry:
    default: nixpkgs
    description: Nix registry to use
    required: false
  sign-commits:
    default: false
    description: Set to true if the action should sign the commit with GPG
  username:
    default: github-actions
    description: Username
runs:
  using: composite
  steps:
    - if: runner.debug == '1'
      run: |
        echo "EXTRA_FLAGS=--debug" >> "$GITHUB_ENV"
      shell: bash
    - id: importGPG
      if: ${{ inputs.sign-commits }}
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
    - env:
        EMAIL: ${{ inputs.email }}
        FULLNAME: ${{ inputs.fullname }}
        REGISTRY: ${{ inputs.registry }}
      run: |
        nix $EXTRA_FLAGS flake update \
          --accept-flake-config
        nix run "$REGISTRY#sapling" -- config \
          --local ui.username "$FULLNAME <$EMAIL>" $EXTRA_FLAGS
      shell: bash
    - env:
        METHOD: ${{ inputs.method }}
      if: ${{ !contains('ghstack,sapling-pull-request,github-pull-request', inputs.method) }}
      run: |
        echo "Unknown update method '$METHOD'. Expected 'ghstack', 'sapling-pull-request' or 'github-pull-request'."
        exit 1
      shell: bash
    - env:
        GPG_KEY_ID: ${{ steps.importGPG.outputs.keyid }}
        REGISTRY: ${{ inputs.registry }}
      if: ${{ inputs.sign-commits && inputs.method == 'sapling-pull-request' }}
      run: |
        nix run "$REGISTRY#sapling" -- config \
          --local commit.gpgsign true \
          --local gpg.key "$GPG_KEY_ID" $EXTRA_FLAGS
      shell: bash
    - env:
        GPG_KEY_ID: ${{ steps.importGPG.outputs.keyid }}
        REGISTRY: ${{ inputs.registry }}
      if: ${{ inputs.sign-commits && inputs.method == 'github-pull-request' }}
      run: |
        nix run "$REGISTRY#jujutsu" -- config set \
          --repo signing.backend gpg $EXTRA_FLAGS
        nix run "$REGISTRY#jujutsu" -- config set \
          --repo signing.sign-all true $EXTRA_FLAGS
        nix run "$REGISTRY#jujutsu" -- config set \
          --repo signing.key "$GPG_KEY_ID" $EXTRA_FLAGS
      shell: bash
    - env:
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        REGISTRY: ${{ inputs.registry }}
      run: |
        nix run "$REGISTRY#sapling" -- ci \
          --message "$COMMIT_MESSAGE" $EXTRA_FLAGS
      shell: bash
    - env:
        GH_TOKEN: ${{ inputs.github-token }}
        USERNAME: ${{ inputs.username }}
      if: inputs.method == 'ghstack'
      run: |
        GHSTACKRC_PATH=$(mktemp)
        cat > "$GHSTACKRC_PATH" <<EOF
        [ghstack]
        github_url = github.com
        github_oauth = $GH_TOKEN
        github_username = $USERNAME
        EOF
        echo "GHSTACKRC_PATH=$GHSTACKRC_PATH" >> "$GITHUB_ENV"
      shell: bash
    - env:
        REGISTRY: ${{ inputs.registry }}
      if: inputs.method == 'ghstack'
      run: |
        nix run "$REGISTRY#ghstack" -- $EXTRA_FLAGS submit
      shell: bash
    - env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REGISTRY: ${{ inputs.registry }}
      if: inputs.method == 'sapling-pull-request'
      run: |
        nix run "$REGISTRY#sapling" -- pr \
          submit $EXTRA_FLAGS
      shell: bash
    - env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REGISTRY: ${{ inputs.registry }}
      continue-on-error: true
      if: inputs.method == 'github-pull-request'
      run: |
        nix run "$REGISTRY#jujutsu" -- git \
          init $EXTRA_FLAGS
      shell: bash
    - env:
        BASE: ${{ inputs.base }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REGISTRY: ${{ inputs.registry }}
        USERNAME: ${{ inputs.username }}
      if: inputs.method == 'github-pull-request'
      run: |
        nix run "$REGISTRY#jujutsu" -- git fetch \
          --remote origin $EXTRA_FLAGS

        nix run "$REGISTRY#jujutsu" -- config set \
          --repo templates.git_push_bookmark \
          "\"$USERNAME/push-\" ++ change_id.short()" $EXTRA_FLAGS

        nix run "$REGISTRY#jujutsu" -- git push \
          --change @ $EXTRA_FLAGS

        PUSH_BRANCH=$(nix run "$REGISTRY#jujutsu" -- log \
          --limit 1 \
          --template "{{bookmarks}}" \
          @ $EXTRA_FLAGS)

        EXISTING=$(gh pr list \
          --head "$PUSH_BRANCH" \
          --base "$BASE" \
          --state open \
          --json number \
          -q '.[0].number' || true)

        if [ -z "$EXISTING" ]; then
          gh pr create \
            --head "$PUSH_BRANCH" \
            --base "$BASE" \
            --title "$COMMIT_MESSAGE" \
            --body "Automated flake update."
        else
          echo "Existing open PR #$EXISTING for $PUSH_BRANCH -> $BASE, not creating a new one."
        fi
      shell: bash
